<a href="https://colab.research.google.com/github/bikumalla/Tensorflow_Deeplearning/blob/main/Tensorflow.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import tensorflow as tf
print(tf.__version__)

2.7.0


In [ ]:
scalar = tf.constant([1,2,3,4,5])
scalar

<tf.Tensor: shape=(5,), dtype=int32, numpy=array([1, 2, 3, 4, 5], dtype=int32)>

In [ ]:
scalar.ndim

1

In [ ]:
vector = tf.constant([[1.0,2.0],[3.0,4.0]],dtype=tf.float16)
vector


<tf.Tensor: shape=(2, 2), dtype=float16, numpy=
array([[1., 2.],
       [3., 4.]], dtype=float16)>

In [ ]:
tensor = tf.constant([[[2,3,4],[4,5,6]],[[6,8,9],[9,5,7]],[[1,2,3],[4,5,6]]])
tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[2, 3, 4],
        [4, 5, 6]],

       [[6, 8, 9],
        [9, 5, 7]],

       [[1, 2, 3],
        [4, 5, 6]]], dtype=int32)>

In [ ]:
tensor.ndim

3

In [ ]:
changable_tensor = tf.Variable([1,3,5])
unchangable_tensor = tf.constant([4,5,6])
changable_tensor,unchangable_tensor

(<tf.Variable 'Variable:0' shape=(3,) dtype=int32, numpy=array([1, 3, 5], dtype=int32)>,
 <tf.Tensor: shape=(3,), dtype=int32, numpy=array([4, 5, 6], dtype=int32)>)

In [ ]:
changable_tensor[0].assign(8)

<tf.Variable 'UnreadVariable' shape=(3,) dtype=int32, numpy=array([8, 3, 5], dtype=int32)>

In [ ]:
changable_tensor

<tf.Variable 'Variable:0' shape=(3,) dtype=int32, numpy=array([8, 3, 5], dtype=int32)>

In [ ]:
random1 = tf.random.Generator.from_seed(32)
random1 = random1.normal(shape=(3,3))
random2 =tf.random.Generator.from_seed(72)
random2 =random2.normal(shape=(3,3))
random1,random2,random1 == random2


(<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
 array([[ 0.7901182 ,  1.585549  ,  0.4356279 ],
        [ 0.23645182, -0.15898712,  1.302304  ],
        [ 0.959224  ,  0.85874265, -1.518177  ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 3), dtype=float32, numpy=
 array([[ 0.21116935, -0.41692957,  0.77891093],
        [ 0.39689952, -1.1513819 ,  0.65339243],
        [ 1.2390149 ,  0.8852658 , -0.67008066]], dtype=float32)>,
 <tf.Tensor: shape=(3, 3), dtype=bool, numpy=
 array([[False, False, False],
        [False, False, False],
        [False, False, False]])>)

In [ ]:
not_shuffled = tf.constant([[2,3],[4,7],[3,8]])
tf.random.shuffle(not_shuffled,seed=45)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[2, 3],
       [3, 8],
       [4, 7]], dtype=int32)>

In [ ]:
tf.random.set_seed(42)
tf.random.shuffle(not_shuffled,seed=42)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[2, 3],
       [4, 7],
       [3, 8]], dtype=int32)>

In [ ]:
tf.ones(shape = (3,3))

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]], dtype=float32)>

In [ ]:
tf.zeros(shape=(3,3))

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]], dtype=float32)>

In [ ]:
import numpy as np
numpy_A = np.arange(1,25)
tensor_A = tf.constant(numpy_A,shape = [2,4,3],dtype=np.int32)
numpy_A,tensor_A

(array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24]),
 <tf.Tensor: shape=(2, 4, 3), dtype=int32, numpy=
 array([[[ 1,  2,  3],
         [ 4,  5,  6],
         [ 7,  8,  9],
         [10, 11, 12]],
 
        [[13, 14, 15],
         [16, 17, 18],
         [19, 20, 21],
         [22, 23, 24]]], dtype=int32)>)

In [ ]:
rank_4_tensor = tf.zeros(shape = [2,3,4,5])
rank_4_tensor

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [ ]:
rank_4_tensor.shape[2]

4

In [ ]:
rank_4_tensor[:2,:2,:2,:]

<tf.Tensor: shape=(2, 2, 2, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [ ]:
rank_2_tensor = tf.constant([[7,10],[4,8]])
rank_2_tensor[:,-1]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  8], dtype=int32)>

In [ ]:
rank_3_tensor = rank_2_tensor[...,tf.newaxis]
rank_2_tensor,rank_3_tensor

(<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[ 7, 10],
        [ 4,  8]], dtype=int32)>,
 <tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
 array([[[ 7],
         [10]],
 
        [[ 4],
         [ 8]]], dtype=int32)>)

In [ ]:
tf.expand_dims(rank_2_tensor,axis=-1)

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[ 7],
        [10]],

       [[ 4],
        [ 8]]], dtype=int32)>

In [ ]:
tensor_2d =tf.constant([[1,2],[3,4]])

In [ ]:
tensor_2d@tensor_2d

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 7, 10],
       [15, 22]], dtype=int32)>

In [ ]:
X = tensor
Y = tf.reshape(tensor,shape = [3,3,2])
Z = tf.transpose(tensor)

In [ ]:
Y

<tf.Tensor: shape=(3, 3, 2), dtype=int32, numpy=
array([[[2, 3],
        [4, 4],
        [5, 6]],

       [[6, 8],
        [9, 9],
        [5, 7]],

       [[1, 2],
        [3, 4],
        [5, 6]]], dtype=int32)>

In [ ]:
A = tf.constant(np.random.randint(low =1,high=144,size=50))

In [ ]:
B =  tf.constant(np.random.random(size=50))
B

<tf.Tensor: shape=(50,), dtype=float64, numpy=
array([0.82785983, 0.72277501, 0.81196953, 0.25208344, 0.60860767,
       0.31279444, 0.12040681, 0.26675777, 0.75173103, 0.28283928,
       0.93469399, 0.10883381, 0.94762075, 0.72251102, 0.42985938,
       0.45364524, 0.78705159, 0.45895925, 0.25940557, 0.60144398,
       0.27801106, 0.88075716, 0.72103642, 0.48962364, 0.97250283,
       0.12101568, 0.54550668, 0.08976488, 0.44110078, 0.4656343 ,
       0.37013252, 0.20959648, 0.01985828, 0.01272567, 0.48618927,
       0.68861049, 0.27237992, 0.44581399, 0.55973194, 0.36211903,
       0.85518766, 0.11586579, 0.59474373, 0.42443416, 0.58946194,
       0.78008385, 0.62895013, 0.98008109, 0.82675648, 0.0024446 ])>

In [ ]:
tf.reduce_min(B)

<tf.Tensor: shape=(), dtype=float64, numpy=0.002444595266830607>

In [ ]:
tf.reduce_mean(A)

<tf.Tensor: shape=(), dtype=int64, numpy=78>

In [ ]:
X

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[2, 3, 4],
        [4, 5, 6]],

       [[6, 8, 9],
        [9, 5, 7]],

       [[1, 2, 3],
        [4, 5, 6]]], dtype=int32)>

In [ ]:
F = tf.constant(np.random.randint(0,100,50),shape = (1, 1, 1, 1, 50))
F.shape,F.ndim

(TensorShape([1, 1, 1, 1, 50]), 5)

In [ ]:
f_squeezed = tf.squeeze(F)
F,f_squeezed

(<tf.Tensor: shape=(1, 1, 1, 1, 50), dtype=int64, numpy=
 array([[[[[24, 29, 19, 94, 34, 78, 64, 81, 64, 12, 13, 23, 53, 69,  1,
            13, 20, 58, 19, 78, 60, 52,  5, 97, 95, 48, 32, 51,  7, 55,
            62, 90, 82,  7, 73, 81, 21, 75,  1,  6,  1, 77, 82, 16, 85,
            89, 95, 28, 83, 47]]]]])>,
 <tf.Tensor: shape=(50,), dtype=int64, numpy=
 array([24, 29, 19, 94, 34, 78, 64, 81, 64, 12, 13, 23, 53, 69,  1, 13, 20,
        58, 19, 78, 60, 52,  5, 97, 95, 48, 32, 51,  7, 55, 62, 90, 82,  7,
        73, 81, 21, 75,  1,  6,  1, 77, 82, 16, 85, 89, 95, 28, 83, 47])>)

In [ ]:
some_list = [0,2,3,3]
tf.one_hot(some_list,depth =4)

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[1., 0., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 1.]], dtype=float32)>

In [ ]:
# Create a simple function
def function(x, y):
  return x ** 2 + y

x = tf.constant(np.arange(0, 10))
y = tf.constant(np.arange(10, 20))
function(x, y)

<tf.Tensor: shape=(10,), dtype=int64, numpy=array([ 10,  12,  16,  22,  30,  40,  52,  66,  82, 100])>

In [ ]:
print(tf.config.list_physical_devices('GPU'))

[PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]


In [ ]:
!nvidia-smi

Sun Jan 30 14:01:25 2022       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 495.46       Driver Version: 460.32.03    CUDA Version: 11.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla K80           Off  | 00000000:00:04.0 Off |                    0 |
| N/A   34C    P0    57W / 149W |    147MiB / 11441MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

# New Section